name: My First Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs: 
  MyFirstJob:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Hey there!"

      - name: Checkout code
        uses: actions/checkout@v6.0.1
      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files: "
          tree
      - name: Set color
        id: color-generator
        run: echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"
      - name: Get color
        run: echo "${{ steps.color-generator.outputs.SELECTED_COLOR }}"
