name: My First Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs: 
  MyFirstJob:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Hey there!"

      - name: Checkout code
        uses: actions/checkout@v6.0.1
      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files: "
          tree
      - name: Set color as output variable
        id: color-generator
        run: echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"
      - name: Get color
        run: echo "${{ steps.color-generator.outputs.SELECTED_COLOR }}"
      - id: sets-a-secret
        name: Generate, mask, and output a secret
        run: |
          the_secret=$((RANDOM))
          echo "::add-mask::$the_secret"
          echo "secret-number=$the_secret" >> "$GITHUB_OUTPUT"
      - name: Use that secret output (protected by a mask)
        run: |
          echo "the secret number is ${{ steps.sets-a-secret.outputs.secret-number }}"
      - name: Set the env value
        id: step_one
        run: |
          echo "action_state=yellow" >> "$GITHUB_ENV"
          echo "${{ env.action_state }}" # This will output 'yellow'
      - name: Set the summary value
        run: |
          echo '### Hello world! :rocket:' >> $GITHUB_STEP_SUMMARY
          echo '### Love this feature! :medal_sports:' >> $GITHUB_STEP_SUMMARY
          echo '<h1>Great feature!</h1>' >> $GITHUB_STEP_SUMMARY

  UsingCompositeAction:
    runs-on: ubuntu-latest
    steps:
      - name: call composite action
      - uses: ././action
        
      
